# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
name: ${PROJECT_NAME}
services:
  minio-server:
    image: minio/minio:RELEASE.2025-02-07T23-21-09Z
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_API_HOST_PORT:-6010}:9000"
      - "${MINIO_CONSOLE_HOST_PORT:-6011}:9001"
    volumes:
      - "${MINIO_MOUNT_PATH:-/mnt/miniodata}:/data"
    command: |
            server /data 
            --address ":9000" 
            --console-address ":9001"

  vdms-vector-db:
    image: intellabs/vdms:v2.10.0
    environment:
      - OVERRIDE_db_root_path=/db
      - OVERRIDE_images_path=/db/images
      - OVERRIDE_descriptors_path=/db/descriptors
      - OVERRIDE_blobs_path=/db/blobs
      - OVERRIDE_pmgd_path=/db/graph
    ports:
      - "${VDMS_VDB_HOST_PORT:-6020}:55555"
    depends_on:
      - minio-server

  vdms-dataprep:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: prod
    image: ${REGISTRY}vdms-dataprep:${TAG:-latest}
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - VDMS_VDB_HOST
      - DEFAULT_BUCKET_NAME
      - MULTIMODAL_EMBEDDING_ENDPOINT
      - VDMS_VDB_PORT=55555
      - APP_HOST=vdms-dataprep # Same as service name. Helps store a URL for video download in metadata.
      - DB_COLLECTION=${INDEX_NAME}
      - MINIO_ENDPOINT=${MINIO_HOST}:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_SECURE=false
    ports:
      - "${VDMS_DATAPREP_HOST_PORT:-6007}:8000"
    depends_on:
      - minio-server

networks:
  default:
    driver: bridge
