x-vippet: &vippet
  image: docker.io/intel/vippet-app:${DOCKER_TAG}
  build:
    context: .
    dockerfile: Dockerfile.vippet
    args:
      http_proxy:
      https_proxy:
      no_proxy:
  ports:
    - "7860:7860"
  healthcheck:
    test: ["CMD", "curl", "--fail", "--silent", "--show-error", "--output", "/dev/null", "http://localhost:7860/"]
    interval: 30s
    timeout: 10s
    retries: 5
  restart: on-failure:5
  environment:
    GST_DEBUG: "1"
    TZ: America/Los_Angeles
    PIPELINE: smartnvr
    MODELS_PATH: /home/dlstreamer/vippet/models
    http_proxy: ${http_proxy}
    https_proxy: ${https_proxy}
    no_proxy: ${no_proxy}
  volumes:
    - collector-signals:/home/dlstreamer/vippet/.collector-signals
    - ./models/output:/home/dlstreamer/vippet/models

services:
  models:
    profiles: [do-not-start]
    image: docker.io/intel/vippet-models:${DOCKER_TAG}
    build:
      context: models
      dockerfile: Dockerfile
      args:
        http_proxy:
        https_proxy:
        no_proxy:
    stdin_open: true
    tty: true
    container_name: models
    volumes:
      - ./models/output/:/output
    environment:
      - MODELS_PATH=/output
      - MODEL_INSTALLATION=${MODEL_INSTALLATION:-once}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
    command: './model_manager.sh'
  vippet-cpu:
    <<: *vippet
    container_name: vippet-cpu
    profiles: [cpu]
  vippet-gpu:
    <<: *vippet
    container_name: vippet-gpu
    group_add:
     - ${RENDER_GROUP_ID}
    devices:
      - "/dev/dri:/dev/dri"
    profiles: [gpu]
  vippet-npu:
    <<: *vippet
    container_name: vippet-npu
    group_add:
     - ${RENDER_GROUP_ID}
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/accel:/dev/accel"
    profiles: [npu]
  collector:
    image: docker.io/intel/vippet-collector:${DOCKER_TAG}
    build:
      context: ./collector
      dockerfile: Dockerfile
      args:
        http_proxy:
        https_proxy:
        no_proxy:
    container_name: collector
    privileged: true
    devices:
      - "/sys:/sys"
      - "/dev:/dev"
      - "/run:/run"
      - "/proc:/proc"
    network_mode: host
    ipc: host
    pid: host
    volumes:
      - "collector-signals:/app/.collector-signals"
    restart: on-failure:5
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
  videogenerator:
    profiles: [do-not-start]
    image: docker.io/intel/vippet-videogenerator:${DOCKER_TAG}
    build:
      context: video_generator
      dockerfile: Dockerfile
      args:
        http_proxy:
        https_proxy:
        no_proxy:
    container_name: videogenerator
    volumes:
      - "./videos:/usr/src/app/output"
      - "./video_generator/config.json:/usr/src/app/config.json"
      - "./video_generator/background.gif:/usr/src/app/background.gif"
      - "./video_generator/images:/usr/src/app/images"
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}

volumes:
  collector-signals:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
