multimodalembeddingms:
  enabled: true
vdmsdataprep:
  enabled: true
vdmsvectordb:
  enabled: true
videosearch:
  enabled: true

global:
  # vdmsIndexName is the DB Index or DB Collection name used by VDMS Vector DB.
  vdmsIndexName: "video_frame_embeddings"

videoSummaryManager:
  env:
    SUMMARY_FEATURE: "FEATURE_OFF"
    SEARCH_FEATURE: "FEATURE_ON"

videosummaryui:
  name: videosummaryui
  feature:
    summary: "FEATURE_OFF"
    search: "FEATURE_ON"
    mux: "ATOMIC"