# DO NOT COMMIT/PUSH THIS FILE TO ANY REPO WITH UPDATED VALUES. IT CAN LEAD TO CREDENTIAL LEAKS.
# RESET ALL THE VALUES HERE TO DEFAULT, BEFORE COMMITING/PUSHING.

global:
  # Update pvcName to a non-empty value if a common PVC storage is desired for application to persist data.
  pvcName: "vss-shared-pvc"

  # Update keepPvc to true if the PVC should be retained after uninstalling the chart.
  # Specifically, set this to true if you want to persist the downloaded models and avoid re-downloading them when re-installing the chart.
  keepPvc: false

  # Update huggingfaceToken if access to gated models is required. (This is needed in case OVMS is used for final summarization)
  huggingfaceToken: ""

  # vlmName is Vision-Language Model Name used by VLM Inference Microservice
  vlmName: ""
  # llmName is Large Language Model Name used by OVMS service
  llmName: ""

  # Update http_proxy and https_proxy with appropriate values if a proxy is required for external access.
  proxy:
    http_proxy: ""
    https_proxy: ""

  env:
    # Update following credentials with a values of your choice - as this is required by respective microservices.
    POSTGRES_USER: ""
    POSTGRES_PASSWORD: ""
    MINIO_ROOT_USER: ""
    MINIO_ROOT_PASSWORD: ""
    RABBITMQ_DEFAULT_USER: ""
    RABBITMQ_DEFAULT_PASS: ""


    # Update these values for telemetry if required. Leave empty if telemetry is not used.
    OTLP_ENDPOINT: ""
    OTLP_ENDPOINT_TRACE: ""

videoingestion:
  # odModelName defines the name of Object Detection Model
  odModelName: ""
  # odModelType defines the type of Object Detection Model. e.g., 'yolo_v8'
  odModelType: ""

multimodalembeddingms:
  # Update textEmbeddingModel for unified video search and summary setup. Keep imageEmbeddingModel empty. See docs for sample value.
  textEmbeddingModel: ""
  # Update imageEmbeddingModel for standalone video search application setup. Keep textEmbeddingModel empty. See docs for sample value.
  imageEmbeddingModel: ""