global:
  proxy:
    no_proxy:
    http_proxy:
    https_proxy:

chatqnaui:
  name: chatqna-ui
  image:
    repository: intel/chatqna-ui
    tag: "1.2.3"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8101
    targetPort: 8101
  env:
    APP_ENDPOINT_URL: "/v1/chatqna"
    APP_DATA_PREP_URL: "/v1/dataprep"
    APP_MAX_TOKENS: 512
