apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.videoSummaryManager.name }}
  labels:
    app: {{ .Values.videoSummaryManager.name }}
spec:
  type: {{ .Values.videoSummaryManager.service.type }}
  ports:
    - port: {{ .Values.videoSummaryManager.service.port }}
      targetPort: {{ .Values.videoSummaryManager.containerPortName }}
      protocol: TCP
  selector:
    app: {{ .Values.videoSummaryManager.name }}
