apiVersion: v1
kind: Service
metadata:
  name: {{ include "videosummaryui.name" . }}
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPortName }}
  selector:
    app: {{ .Values.name }}
