apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.audioanalyzer.name }}
  labels:
    app: {{ include "audioanalyzer.name" . }}
spec:
  type: {{ .Values.audioanalyzer.service.type }}
  selector:
    app: {{ .Values.audioanalyzer.name }}
  ports:
    - port: {{ .Values.audioanalyzer.service.port }}
      targetPort: {{ .Values.audioanalyzer.containerPortName }}
      name: {{ .Values.audioanalyzer.service.portName }}