apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "audioanalyzer.fullname" . }}
  labels:
    app: {{ include "audioanalyzer.name" . }}
spec:
  replicas: {{ .Values.audioanalyzer.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.audioanalyzer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.audioanalyzer.name }}
    spec:
      {{- with .Values.nodeAffinity }}
      affinity:
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      containers:
        - name: {{ .Values.audioanalyzer.name }}
          image: "{{ .Values.audioanalyzer.image.repository }}:{{ .Values.audioanalyzer.image.tag }}"
          imagePullPolicy: {{ .Values.audioanalyzer.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.audioanalyzer.containerPort }}
              name: {{ .Values.audioanalyzer.containerPortName }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          env:
            - name: DEBUG
              value: {{ .Values.audioanalyzer.env.DEBUG | quote }}
            - name: DEFAULT_DEVICE
              value: {{ .Values.audioanalyzer.env.DEFAULT_DEVICE | quote }}
            - name: DEFAULT_WHISPER_MODEL
              value: {{ .Values.audioanalyzer.env.DEFAULT_WHISPER_MODEL | quote }}
            - name: ENABLED_WHISPER_MODELS
              value: {{ .Values.audioanalyzer.env.ENABLED_WHISPER_MODELS | quote }}
            - name: MAX_FILE_SIZE
              value: {{ .Values.audioanalyzer.env.MAX_FILE_SIZE | quote }}
            - name: MINIO_ENDPOINT
              value: "{{ .Values.minioServer.name }}:{{ .Values.minioServer.service.port }}"
            - name: MINIO_HOST
              value: "{{ .Values.minioServer.name }}"
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.global.env.MINIO_ROOT_USER | quote }}
            - name: MINIO_SECRET_KEY
              value: {{ .Values.global.env.MINIO_ROOT_PASSWORD | quote }}
            - name: STORAGE_BACKEND
              value: {{ .Values.audioanalyzer.env.STORAGE_BACKEND | quote }}
            - name: USE_FP16
              value: {{ .Values.audioanalyzer.env.USE_FP16 | quote }}
            - name: http_proxy
              value: {{ .Values.global.proxy.http_proxy | quote }}
            - name: https_proxy
              value: {{ .Values.global.proxy.https_proxy | quote }}
            - name: no_proxy
              value: "{{ .Values.global.proxy.no_proxy }},localhost,127.0.0.1,audioanalyzer,vlm-inference-microservice,videosummarybackend,videoingestion,minio-server,postgresql,video-summary-nginx,rabbitmq,multimodal-embedding-ms,vdms-dataprep,vdms-vectordb,videosearch,.svc.cluster.local"
          volumeMounts:
            - name: data-volume
              mountPath: /home/appuser/data
              subPath: audioanalyzer/data
            - name: data-volume
              mountPath: /home/appuser/models
              subPath: audioanalyzer/models
      volumes:
        - name: data-volume
          {{- if .Values.global.pvcName }}
          persistentVolumeClaim:
            claimName: {{ .Values.global.pvcName }}
          {{- else if .Values.global.volumeHostPath }}
          hostPath:
            path: {{ .Values.global.volumeHostPath }}
            type: DirectoryOrCreate
          {{- else }}
          emptyDir: {}
          {{- end }}