apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vdms-vectordb.fullname" . }}-config
  labels:
    {{- include "vdms-vectordb.labels" . | nindent 4 }}
data:
  OVERRIDE_port: {{ .Values.containerPort | quote }}
  OVERRIDE_images_path: db/images
  OVERRIDE_descriptors_path: db/descriptors
  OVERRIDE_blobs_path: db/blobs
  OVERRIDE_pmgd_path: db/graph