# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  vlm-openvino-serving:
    image: ${REGISTRY:-}vlm-openvino-serving:${TAG:-latest}
    container_name: vlm-openvino-serving
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${VLM_SERVICE_PORT}:8000"
    ipc: host
    environment:
      no_proxy_env: ${no_proxy_env},${HOST_IP}
      no_proxy: ${no_proxy_env},${HOST_IP}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      VLM_MODEL_NAME: ${VLM_MODEL_NAME}
      VLM_COMPRESSION_WEIGHT_FORMAT: ${VLM_COMPRESSION_WEIGHT_FORMAT}
      VLM_DEVICE: ${VLM_DEVICE}
      VLM_SEED: ${VLM_SEED}
      WORKERS: ${WORKERS:-1}
      VLM_MAX_COMPLETION_TOKENS: ${VLM_MAX_COMPLETION_TOKENS}
      HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
      OV_CONFIG: ${OV_CONFIG}
      VLM_LOG_LEVEL: ${VLM_LOG_LEVEL:-info}
      OPENVINO_LOG_LEVEL: ${VLM_OPENVINO_LOG_LEVEL:-1}
      VLM_ACCESS_LOG_FILE: ${VLM_ACCESS_LOG_FILE:-/dev/null}
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - ${USER_GROUP_ID:-1000} 
      - ${VIDEO_GROUP_ID:-44}    
      - ${RENDER_GROUP_ID:-1002}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 40
      start_period: 10s
    networks:
      - my_network
    volumes:
      - ov-models:/home/appuser/.cache/huggingface
      - ov-models:/app/ov-model
volumes:
  ov-models:
    external: true

networks:
  my_network:
    driver: bridge