global:
  # Set this value to hostPath where we want to mount a volume (Used in single node cluster or standalone sub-chart installation).
  volumeHostPath: "/mnt/minio"
  # pvcName is the name of common PVC used by multiple microservices for persisting models, cache and other files.
  pvcName: ""
  proxy:
    no_proxy:
    http_proxy:
    https_proxy:
  env:
    MINIO_ROOT_USER:
    MINIO_ROOT_PASSWORD:

name: minio-server
image:
  repository: minio/minio
  tag: RELEASE.2025-02-07T23-21-09Z-cpuv1
  pullPolicy: IfNotPresent

containerApiPortName: api-port  # Optional name to refer apiPort
containerConsolePortName: console-port  # Optional name to refer consolePort
service:
  type: ClusterIP
  consolePort: 9001  # Port on which service listens for incoming connection for Console application
  apiPort: 9000  # Port on which service listens for incoming connection for API application
