apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "multimodal-embedding-ms.fullname" . }}
  labels:
    {{- include "multimodal-embedding-ms.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "multimodal-embedding-ms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "multimodal-embedding-ms.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        fsGroup: {{ .Values.gpu.videoGroupID }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeAffinity }}
      affinity:
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ ternary .Values.image.gpu.repository .Values.image.cpu.repository .Values.gpu.enabled }}:{{ ternary .Values.image.tag .Values.global.commonTag (empty .Values.global.commonTag) | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.containerPortName }}
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- if eq .Values.useOnlyTextEmbeddings true }}
            {{- toYaml .Values.startupProbeWithTextEmbeddingModel | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.startupProbe | nindent 12 }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "multimodal-embedding-ms.fullname" . }}-config
          env:
            - name: EMBEDDING_DEVICE
              value: {{ if .Values.gpu.enabled }}"GPU"{{ else }}"CPU"{{ end }}
            - name: EMBEDDING_USE_OV
              value: {{ if .Values.gpu.enabled }}"true"{{ else }}"false"{{ end }}
          securityContext:
            runAsUser: 0
            runAsGroup: {{ .Values.gpu.renderGroupID }}
            {{- if .Values.gpu.group_add }}
            capabilities:
              add:
                {{- toYaml .Values.gpu.group_add | nindent 16 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: volume-data
              mountPath: /home/appuser/.cache/huggingface
              subPath: huggingface
            - name: volume-data
              mountPath: /app/ov-models
              subPath: ov-models/embeddingms
            - name: volume-data
              mountPath: /tmp/dataprep
              subPath: dataprep
            {{- if .Values.gpu.enabled }}
            - name: gpu-devices
              mountPath: /dev/dri
            {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: volume-data
          {{- if .Values.global.pvcName }}
          persistentVolumeClaim:
            claimName: {{ .Values.global.pvcName }}
          {{- else if .Values.global.volumeHostPath }}
          hostPath:
            path: {{ .Values.global.volumeHostPath }}
            type: DirectoryOrCreate
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.gpu.enabled }}
        - name: gpu-devices
          hostPath:
            path: /dev/dri
            type: Directory
        {{- end }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}