apiVersion: v1
kind: Service
metadata:
  name: multimodal-embedding-ms
  labels:
    {{- include "multimodal-embedding-ms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPortName }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{ include "multimodal-embedding-ms.selectorLabels" . | nindent 4 }}