apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.videoingestion.name }}
  labels:
    app: {{ include "videoingestion.name" . }}
spec:
  type: {{ .Values.videoingestion.service.type }}
  ports:
    - port: {{ .Values.videoingestion.service.port }}
      targetPort: {{ .Values.videoingestion.containerPortName }}
      protocol: TCP
      name: {{ .Values.videoingestion.service.portName }}
  selector:
    app: {{ include "videoingestion.name" . }}


