apiVersion: v1
kind: Service
metadata:
  name: "vdms-dataprep"
  labels:
    {{ include "vdms-dataprep.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPortName }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  
  selector:
    {{- include "vdms-dataprep.selectorLabels" . | nindent 4 }}
