# Default values for VDMS DataPrep Service.

replicaCount: 1

image:
  repository: intel/vdms-dataprep
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.2.1"

imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: false
  runAsUser: 0
  seccompProfile:
    type: RuntimeDefault    

containerPort: 8000   # Port on which container application listens internally
containerPortName: dataprep-port    # Optional name to refer containerPort
service:
  type: ClusterIP
  port: 8000    # Port on which service listens for incoming connection, if exposed externally
  portName: http    # Service port name. Useful when service exposes multiple ports.

resources: {}

livenessProbe:
  httpGet:
    path: /health
    port: dataprep-port
  initialDelaySeconds: 20
  periodSeconds: 20
  failureThreshold: 6
readinessProbe:
  httpGet:
    path: /health
    port: dataprep-port
  initialDelaySeconds: 10
  periodSeconds: 20
  failureThreshold: 6
startupProbe:
  httpGet:
    path: /health
    port: dataprep-port
  initialDelaySeconds: 10
  periodSeconds: 20
  failureThreshold: 6

nodeSelector: {}
tolerations: []
affinity: {}

# Values required to configure DataPrep service
indexName: "videosearch-index"
vdmsVectorDbHost: "vdms-vectordb"
vdmsVectorDbPort: 55555
multimodalEmbeddingModelName: "openai/clip-vit-base-patch32"
multimodalEmbeddingNumFrames: 64

global:
  # Set this value to hostPath where we want to mount a volume (Used in single node cluster or standalone sub-chart installation).
  volumeHostPath: "/mnt/dataprep"

  # pvcName is the name of common PVC used by multiple microservices for persisting models, cache and other files.
  pvcName: ""
  
  # Nodes on which pods using the PV will be scheduled
  storageNodeAffinity: []

  # Common release tags to be used for several dependencies 
  commonTag: ""

  # vdmsIndexName is the DB Index or DB Collection name used by VDMS Vector DB.
  vdmsIndexName: ""
  
  proxy:
  # setup proxy settings
    no_proxy: ""
    http_proxy: ""
    https_proxy: ""
  env:
    MINIO_ROOT_USER:
    MINIO_ROOT_PASSWORD:


minioServer:
  name: minio-server
  service:
    type: ClusterIP
    port: 9000
    targetPort: 9000