global:
  # Set this value to hostPath where we want to mount a volume (Used in single node cluster or standalone sub-chart installation).
  volumeHostPath: "/mnt/audioanalyzer"
  # pvcName is the name of common PVC used by multiple microservices for persisting models, cache and other files.
  pvcName: ""
  
  proxy:
    http_proxy: 
    https_proxy: 
    no_proxy:
  env:
    MINIO_SERVER:
    MINIO_HOST:
    MINIO_ROOT_USER: 
    MINIO_ROOT_PASSWORD:


audioanalyzer:
  name: audioanalyzer
  image:
    repository: intel/audio-analyzer
    tag: "1.2.1"
    pullPolicy: IfNotPresent
  env:
    DEBUG: "false"
    DEFAULT_DEVICE: "cpu"
    MAX_FILE_SIZE: "314572800"
    STORAGE_BACKEND: minio
    ENABLED_WHISPER_MODELS: "small.en,tiny.en,medium.en"
    DEFAULT_WHISPER_MODEL: "small.en"
    USE_FP16: "true"

  containerPort: 8000  # Port on which container application listens internally
  containerPortName: audio-port # Optional name to refer containerPort
  service:
    port: 8000    # Port on which service listens for incoming connection, if exposed externally
    type: ClusterIP
    portName: http    # Service port name. Useful when service exposes multiple ports.

minioServer:
  name: minio-server
  service:
    type: ClusterIP
    port: 9000
    targetPort: 9000


livenessProbe:
  httpGet:
    path: /api/v1/health
    port: audio-port
  initialDelaySeconds: 10
  periodSeconds: 20
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /api/v1/health
    port: audio-port
  initialDelaySeconds: 5
  periodSeconds: 20
  failureThreshold: 3

# Wait for startup till max ~ 45Mins 
startupProbe:
  httpGet:
    path: /api/v1/health
    port: audio-port
  initialDelaySeconds: 10
  periodSeconds: 30
  failureThreshold: 90

# Node affinity to schedule pods on specific nodes only
nodeAffinity: {}