global:
  huggingface:
    apiToken:   # Set this during installation
  proxy:
    no_proxy: 
    http_proxy: 
    https_proxy: 
  LLM_MODEL: 

ovms:
  name: ovms
  image:
    repository: openvino/model_server
    tag: "2025.3"
    Gputag: "2025.3-gpu"
    pullPolicy: IfNotPresent
  readinessProbe:
    httpGet:
      path: /v2/health/ready
      port: 8300
    initialDelaySeconds: 60
    periodSeconds: 30
  service:
    type: ClusterIP
    port: 8300
    targetPort: 8300
  group_add: $(stat -c "%g" /dev/dri/render*)
  # scriptconfigmap: ovms-configmap.yaml
  env:
    WEIGHT_FORMAT: "int8"
    model_directory_name: "converted_model"
  script:
    name: "ovms-model-preparation"
