apiVersion: v1
kind: Service
metadata:
  name: {{ include "minioserver.name" . }}
  labels:
    app: {{ include "minioserver.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: console-port
      port: {{ .Values.service.consolePort }}
      targetPort: {{ .Values.containerConsolePortName }}
    - name: api-port
      port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.containerApiPortName }}
  selector:
    app: {{ .Values.name }}