---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge CI Pipeline

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - release-*
  workflow_dispatch:

permissions: {}

jobs:
  filter:
    permissions:
      contents: read          # needed for actions/checkout
    runs-on: ubuntu-latest
    outputs:
      dlstreamer-pipeline-server_changed: ${{ steps.filter.outputs.dlstreamer-pipeline-server }}
      document-ingestion_changed: ${{ steps.filter.outputs.document-ingestion }}
      document-summarization_changed: ${{ steps.filter.outputs.document-summarization }}
      model-registry_changed: ${{ steps.filter.outputs.model-registry }}
      chat-question-and-answer_changed: ${{ steps.filter.outputs.chat-question-and-answer }}
      visual-pipeline-platform-tool_changed: ${{ steps.filter.outputs.visual-pipeline-platform-tool }}
      chat-question-and-answer-core_changed: ${{ steps.filter.outputs.chat-question-and-answer-core }}
      time-series-analytics-docs_changed: ${{ steps.filter.outputs.time-series-analytics-docs }}
      plcopen-motion-control_changed: ${{ steps.filter.outputs.plcopen-motion-control }}
      video-summarization_changed: ${{ steps.filter.outputs.video-summarization }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set paths filter
        id: filter
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        with:
          filters: |
            dlstreamer-pipeline-server:
              - 'microservices/dlstreamer-pipeline-server/docs/**'
            document-ingestion:
              - 'microservices/document-ingestion/pgvector/docs/**'
            document-summarization:
              - 'sample-applications/document-summarization/docs/**'
            model-registry:
              - 'microservices/model-registry/docs/**'
            chat-question-and-answer:
              - 'sample-applications/chat-question-and-answer/docs/**'
            visual-pipeline-platform-tool:
              - 'tools/visual-pipeline-and-platform-evaluation-tool/docs/**'
            chat-question-and-answer-core:
              - 'sample-applications/chat-question-and-answer-core/docs/**'
            time-series-analytics-docs:
              - 'microservices/time-series-analytics/docs/**'
            plcopen-motion-control:
              - 'libraries/edge-control-libraries/plcopen-motion-control/docs/**'
            video-summarization:
              - 'sample-applications/video-search-and-summarization/docs/**'

  build_dlstreamer-pipeline-server:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    needs: filter
    if: ${{ needs.filter.outputs.dlstreamer-pipeline-server_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@a77655e8fbb08f0d8e500a451aa0025bec249803
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: microservices/dlstreamer-pipeline-server

  build_document-ingestion:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    needs: filter
    if: ${{ needs.filter.outputs.document-ingestion_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@a77655e8fbb08f0d8e500a451aa0025bec249803
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: microservices/document-ingestion/pgvector

  build_document-summarization:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    needs: filter
    if: ${{ needs.filter.outputs.document-summarization_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@a77655e8fbb08f0d8e500a451aa0025bec249803
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: sample-applications/document-summarization
      branch_pattern: '(?!release-1\.0\.0)(^(main|release-.*)$)'  # Does not exist on release-1.0.0 branch - Exclude it

  build_model-registry:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    needs: filter
    if: ${{ needs.filter.outputs.model-registry_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@a77655e8fbb08f0d8e500a451aa0025bec249803
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: microservices/model-registry

  build_chat-question-and-answer:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    needs: filter
    if: ${{ needs.filter.outputs.chat-question-and-answer_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@a77655e8fbb08f0d8e500a451aa0025bec249803
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: sample-applications/chat-question-and-answer

  build_visual-pipeline-platform-tool:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    needs: filter
    if: ${{ needs.filter.outputs.visual-pipeline-platform-tool_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@a77655e8fbb08f0d8e500a451aa0025bec249803
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: tools/visual-pipeline-and-platform-evaluation-tool

  build_chat-question-and-answer-core:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    needs: filter
    if: ${{ needs.filter.outputs.chat-question-and-answer-core_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@a77655e8fbb08f0d8e500a451aa0025bec249803
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: sample-applications/chat-question-and-answer-core

  build_time-series-analytics-docs:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    needs: filter
    if: ${{ needs.filter.outputs.time-series-analytics-docs_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@a77655e8fbb08f0d8e500a451aa0025bec249803
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: microservices/time-series-analytics
      branch_pattern: '(?!release-1\.0\.0)(^(main|release-.*)$)'  # Does not exist on release-1.0.0 branch - Exclude it

  build_plcopen-motion-control:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    needs: filter
    if: ${{ needs.filter.outputs.plcopen-motion-control_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@a77655e8fbb08f0d8e500a451aa0025bec249803
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: libraries/edge-control-libraries/plcopen-motion-control
      branch_pattern: '(?!release-1\.0\.0)(^(main|release-.*)$)'  # Does not exist on release-1.0.0 branch - Exclude it

  build_video-summarization:
    permissions:
      contents: read          # needed for actions/checkout
      pull-requests: read     # needed for gh pr list
      issues: write           # needed to post PR comment
    needs: filter
    if: ${{ needs.filter.outputs.video-summarization_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@a77655e8fbb08f0d8e500a451aa0025bec249803
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: sample-applications/video-search-and-summarization
      branch_pattern: '(?!release-1\.0\.0)(^(main|release-.*)$)'  # Does not exist on release-1.0.0 branch - Exclude it
