---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Pre-Merge CI Pipeline

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:

permissions: {}

jobs:
  filter:
    permissions:
      contents: read          # needed for actions/checkout
    runs-on: ubuntu-latest
    outputs:
      audio-analyzer_changed: ${{ steps.filter.outputs.audio-analyzer }}
      dlstreamer-pipeline-server_changed: ${{ steps.filter.outputs.dlstreamer-pipeline-server }}
      document-summarization_changed: ${{ steps.filter.outputs.document-summarization }}
      model-registry_changed: ${{ steps.filter.outputs.model-registry }}
      chat-question-and-answer_changed: ${{ steps.filter.outputs.chat-question-and-answer }}
      visual-pipeline-platform-tool_changed: ${{ steps.filter.outputs.visual-pipeline-platform-tool }}
      chat-question-and-answer-core_changed: ${{ steps.filter.outputs.chat-question-and-answer-core }}
      time-series-analytics-docs_changed: ${{ steps.filter.outputs.time-series-analytics-docs }}
      plcopen-motion-control_changed: ${{ steps.filter.outputs.plcopen-motion-control }}
      vector-retriever_changed: ${{ steps.filter.outputs.vector-retriever }}
      video-summarization_changed: ${{ steps.filter.outputs.video-summarization }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set paths filter
        id: filter
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        with:
          filters: |
            audio-analyzer:
              - 'microservices/audio-analyzer/docs/**'
            dlstreamer-pipeline-server:
              - 'microservices/dlstreamer-pipeline-server/docs/**'
            document-summarization:
              - 'sample-applications/document-summarization/docs/**'
            model-registry:
              - 'microservices/model-registry/docs/**'
            chat-question-and-answer:
              - 'sample-applications/chat-question-and-answer/docs/**'
            visual-pipeline-platform-tool:
              - 'tools/visual-pipeline-and-platform-evaluation-tool/docs/**'
            chat-question-and-answer-core:
              - 'sample-applications/chat-question-and-answer-core/docs/**'
            time-series-analytics-docs:
              - 'microservices/time-series-analytics/docs/**'
            plcopen-motion-control:
              - 'libraries/edge-control-libraries/plcopen-motion-control/docs/**'
            vector-retriever:
              - 'microservices/vector-retriever/milvus/docs/**'
            video-summarization:
              - 'sample-applications/video-search-and-summarization/docs/**'

  build_audio-analyzer:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.audio-analyzer_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: microservices/audio-analyzer
      exclude_patterns: "**/user-guide/Overview.md"

  build_dlstreamer-pipeline-server:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.dlstreamer-pipeline-server_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: microservices/dlstreamer-pipeline-server
      exclude_patterns: "**/user-guide/Overview.md"

  build_document-summarization:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.document-summarization_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: sample-applications/document-summarization
      exclude_patterns: "**/user-guide/Overview.md"

  build_model-registry:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.model-registry_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: microservices/model-registry
      exclude_patterns: "**/user-guide/Overview.md"

  build_chat-question-and-answer:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.chat-question-and-answer_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@cd8df4807e6a736f181d20e69ba25791be1e11d7
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: sample-applications/chat-question-and-answer
      exclude_patterns: "**/user-guide/overview.md"

  build_visual-pipeline-platform-tool:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.visual-pipeline-platform-tool_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: tools/visual-pipeline-and-platform-evaluation-tool
      exclude_patterns: "**/user-guide/Overview.md"

  build_chat-question-and-answer-core:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.chat-question-and-answer-core_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@cd8df4807e6a736f181d20e69ba25791be1e11d7
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: sample-applications/chat-question-and-answer-core

  build_time-series-analytics-docs:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.time-series-analytics-docs_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: microservices/time-series-analytics
      exclude_patterns: "**/user-guide/Overview.md"

  build_plcopen-motion-control:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.plcopen-motion-control_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: libraries/edge-control-libraries/plcopen-motion-control

  build_vector-retriever:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.vector-retriever_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: microservices/vector-retriever/milvus
      exclude_patterns: "**/user-guide/Overview.md"

  build_video-summarization:
    permissions:
      contents: read          # needed for actions/checkout
    needs: filter
    if: ${{ needs.filter.outputs.video-summarization_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/build-documentation.yml@b14b0105bf312a2c98457dd021622de4c14f6bff
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: sample-applications/video-search-and-summarization
      exclude_patterns: "**/user-guide/Overview.md"
